# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Common\:
        resource: '../src/Common/'
        exclude:
            - '../src/Common/Domain/'
    User\:
        resource: '../src/User/'
        exclude:
            - '../src/User/Application/Dto/'
            - '../src/User/Domain/Entities'
            - '../src/User/Domain/ValueObjects'
            - '../src/User/Domain/Events'
    Credit\:
        resource: '../src/Credit/'
        exclude:
            - '../src/Credit/Application/Dto/'
            - '../src/Credit/Domain/Entities'
            - '../src/Credit/Domain/ValueObjects'
            - '../src/Credit/Domain/Events'
            - '../src/Credit/Domain/Exceptions'
    Notifier\:
        resource: '../src/Notifier/'
        exclude:
            - '../src/Notifier/Application/Dto/'
            - '../src/Notifier/Domain/Entities'
            - '../src/Notifier/Domain/ValueObjects'
            - '../src/Notifier/Domain/Events'
            - '../src/Notifier/Domain/Exceptions'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
